FROM golang:1.22-alpine AS build
WORKDIR /src
COPY go.mod ./
COPY go.sum* ./
RUN go mod download || true
COPY . .
RUN CGO_ENABLED=0 GOFLAGS=-trimpath go build \
    -ldflags='-s -w' -o /out/storaged ./cmd/storaged

FROM gcr.io/distroless/static-debian12
COPY --from=build /out/storaged /storaged
EXPOSE 9982
ENTRYPOINT ["/storaged"]
